### ISSUE TITLE
Policy on adding functionality to tradingAPI?

### ISSUE THREAD

**Issue by Gondee** [gazbert/bxbot#46]
What is your take on adding methods to the tradingAPI interface. I have several bots running in  "record mode" that use API calls that are currently not supported. Example: getting all trades market wide. Now I have modified my trading API to support this function, but only have one exchange supporting the call at the moment. Would love to share this then have others potentially fill in exchanges that I don't use if this adheres to @gazbert policies. I will be adding more exchange support as I transition my bot onto more exchanges if that helps

**Comment by gazbert** [comment]
Hey Josh, adding more meaningful methods is more than welcome! I started off with the bare-bones minimum in the Trading API to get people up and running fast... but as new requirements (like yours) come in, it should evolve... :-) 

Ideally, any new ops added should potentially be 'implementable' by the existing adapters, so we can try and maintain a consistent expectation (for the user of the API) across multiple exchanges. Having said that, if there's a strong case for an op that, say, only 2/8 exchanges could only fulfil (due to limitations in the actual exchange API), we'll deal with each case on its merits.

Best approach would be to stick a default 'no-op' method on the TradingApi interface for any new stuff you add. That way, the existing adapters will still build... until/if we get round to implementing the method. All new ops on the interface will need unit tests/integration tests/Javadoc/README user guide updates... zzzzzz, I know, but someone's gotta do it ;-)

At some point I was going to look at adding withdrawls to the API too.

As always, no rush for any of this stuff, just have fun coding :-)

**Comment by Gondee** [comment]
I see, thanks for clearing that up. Ill put in some pull requests in soon.

Thanks man, I am having fun ahah, I have a light last semester of college and this project is a similar stack to the one I got hired to work on next year. So its the perfect project for me to learn and have fun atm! 

I have numerous other changes that have helped my bot become profitable that I would like to contribute as well, so Ill put those in as pull requests and you can add them per your ideas about how the bot should work :)

Also I am having trouble adding MongoDB to Gradel/Marven such that it builds. I have it working via Intellij's built in adding library functionality (but of course that wont build to place on my linux VM's). Do you have any tips on how to accomplish this the way you have this project setup. I have tried various solutions online, but I could not get anything operational. 

Best,
Joshua

**Comment by gazbert** [comment]
Closing - see https://github.com/gazbert/bxbot/blob/master/CONTRIBUTING.md
